---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  firefox: "55.0"

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - yarn install --no-lockfile --non-interactive

script:
  - node_modules/.bin/ember test
